### ISSUE TITLE
No data displayed

### ISSUE THREAD

**Issue by infernix** [neftaly/kgauge#2]
Running this on Openplotter, I can see the stream data coming in just fine, but no data is rendered. No error messages on java console. Just nothing.

Even if i delete all gauges and add just `navigation.attitude.pitch` (from the IMU), nothing is shown.

Any suggestions?

**Comment by neftaly** [comment]
Oh, I must have broken something in the last build. Sorry about that, I might delete/deprecate the repo.

**Comment by infernix** [comment]
I don't think that's it. I've reverted to each commit until the initial one, and it's all the same. I'm thinking maybe something changed in the ws stream that needs adjustment on the parsing side?

**Comment by infernix** [comment]
OK, I got as far as 

```diff
diff --git a/package.json b/package.json
index 7ebf228..c3affbe 100644
--- a/package.json
+++ b/package.json
@@ -30,7 +30,7 @@
     "react": "^16.0.0",
     "react-dom": "^16.0.0",
     "recompose": "^0.26.0",
-    "signalk-schema": "0.0.1-3"
+    "@signalk/signalk-schema": "1.0.3"
   },
   "devDependencies": {
     "babel-core": "^6.26.0",
diff --git a/src/Main/Gauges/getSchemaMeta.js b/src/Main/Gauges/getSchemaMeta.js
index 240c7b1..429f4ed 100644
--- a/src/Main/Gauges/getSchemaMeta.js
+++ b/src/Main/Gauges/getSchemaMeta.js
@@ -1,5 +1,5 @@
 import * as R from 'ramda';
-import metadata from 'signalk-schema/keyswithmetadata.json';
+import metadata from '@signalk/signalk-schema/dist/keyswithmetadata.json';
 import { fromJS } from 'immutable';
 import memoizee from 'memoizee';
 
```

I bet the problem is this change https://github.com/SignalK/specification/issues/391 (fixed elsewhere like this https://github.com/ph1l/python-signalk-client/commit/18033f6c47b6324bfa22d39439cc21d19bb6f690) but I know nothing about react. Probably trivial for you to fix?

**Comment by neftaly** [comment]
Geez that is definitely a breaking change in the spec. Thanks for creating this issue.
